//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMI.Web.Frontend.API.Tests {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMI.Web.Frontend.API.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;Version&quot; :
        ///	{
        ///		&quot;date&quot; : &quot;20170615&quot;
        ///	},
        ///	&quot;Enums&quot; :
        ///	{
        ///		&quot;Benutzbarkeit&quot; :
        ///		{
        ///			&quot;1&quot; :
        ///			{
        ///				&quot;Name&quot; : &quot;FreiEinsehbar&quot;
        ///			},
        ///			&quot;2&quot; :
        ///			{
        ///				&quot;Name&quot; : &quot;TeilweiseGesuchspflichtig&quot;
        ///			},
        ///			&quot;3&quot; :
        ///			{
        ///				&quot;Name&quot; : &quot;Gesuchspflichtig&quot;
        ///			}
        ///		}
        ///	},
        ///	&quot;Types&quot; :
        ///	{
        ///		&quot;Base&quot; :
        ///		{
        ///			&quot;Meta&quot; :
        ///			{
        ///				&quot;Identifikation&quot; :
        ///				{
        ///					&quot;Fields&quot; : [
        ///						&quot;ReferenceCode&quot;,
        ///						&quot;Level&quot;,
        ///						{
        ///							&quot;key&quot; : &quot;CreationPeriod&quot;,
        ///							&quot;type&quot; : &quot;Date.Range&quot;
        ///						}
        ///					]
        ///				}, [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string modelData {
            get {
                return ResourceManager.GetString("modelData", resourceCulture);
            }
        }
    }
}
