//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMI.Access.Harvest.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMI.Access.Harvest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        internal static string BooleanNo {
            get {
                return ResourceManager.GetString("BooleanNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        /// </summary>
        internal static string BooleanYes {
            get {
                return ResourceManager.GetString("BooleanYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ab {0} ähnelt.
        /// </summary>
        internal static string TimeRangeFormatter_Ab {
            get {
                return ResourceManager.GetString("TimeRangeFormatter_Ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bis {0} ähnelt.
        /// </summary>
        internal static string TimeRangeFormatter_Bis {
            get {
                return ResourceManager.GetString("TimeRangeFormatter_Bis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}. Jh. ähnelt.
        /// </summary>
        internal static string TimeRangeFormatter_Century {
            get {
                return ResourceManager.GetString("TimeRangeFormatter_Century", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ca. {0} ähnelt.
        /// </summary>
        internal static string TimeRangeFormatter_Circa {
            get {
                return ResourceManager.GetString("TimeRangeFormatter_Circa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ähnelt.
        /// </summary>
        internal static string TimeRangeFormatter_Genau {
            get {
                return ResourceManager.GetString("TimeRangeFormatter_Genau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die keine Angabe ähnelt.
        /// </summary>
        internal static string TimeRangeFormatter_KeineAngabe {
            get {
                return ResourceManager.GetString("TimeRangeFormatter_KeineAngabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nach {0} ähnelt.
        /// </summary>
        internal static string TimeRangeFormatter_Nach {
            get {
                return ResourceManager.GetString("TimeRangeFormatter_Nach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die s. d. (sine dato) ähnelt.
        /// </summary>
        internal static string TimeRangeFormatter_SineDato {
            get {
                return ResourceManager.GetString("TimeRangeFormatter_SineDato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} - {1} ähnelt.
        /// </summary>
        internal static string TimeRangeFormatter_VonBis {
            get {
                return ResourceManager.GetString("TimeRangeFormatter_VonBis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die vor {0} ähnelt.
        /// </summary>
        internal static string TimeRangeFormatter_Vor {
            get {
                return ResourceManager.GetString("TimeRangeFormatter_Vor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} v.Chr. ähnelt.
        /// </summary>
        internal static string TimeRangeFormatter_VorChristus {
            get {
                return ResourceManager.GetString("TimeRangeFormatter_VorChristus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die zwischen {0} und {1} ähnelt.
        /// </summary>
        internal static string TimeRangeFormatter_Zwischen {
            get {
                return ResourceManager.GetString("TimeRangeFormatter_Zwischen", resourceCulture);
            }
        }
    }
}
