//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMI.Utilities.Transkribus.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class TranskribusSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TranskribusSettings defaultInstance = ((TranskribusSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TranskribusSettings())));
        
        public static TranskribusSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@CMI.Utilities.Transkribus.Properties.TranskribusParameterSettings@@")]
        public string TranskribusParameterSettings {
            get {
                return ((string)(this["TranskribusParameterSettings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@CMI.Utilities.Transkribus.Properties.TranskribusTimeOut@@")]
        public string TranskribusTimeOut {
            get {
                return ((string)(this["TranskribusTimeOut"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TW90rP8fVTtpf3Vjxefo")]
        public string TranskribusSftpPassword {
            get {
                return ((string)(this["TranskribusSftpPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TranskribusSftpHost {
            get {
                return ((string)(this["TranskribusSftpHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TranskribusSFTPKeyFile {
            get {
                return ((string)(this["TranskribusSFTPKeyFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sftp_htruser")]
        public string TrankribusSFTPUser {
            get {
                return ((string)(this["TrankribusSFTPUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TranskribusSftpPort {
            get {
                return ((string)(this["TranskribusSftpPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@CMI.Utilities.Transkribus..Properties.TranskribusBindPathInput@@")]
        public string TranskribusBindPathInput {
            get {
                return ((string)(this["TranskribusBindPathInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@CMI.Utilities.Transkribus.Properties.TranskribusBindPathOutput@@")]
        public string TranskribusBindPathOutput {
            get {
                return ((string)(this["TranskribusBindPathOutput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BaseDirectory {
            get {
                return ((string)(this["BaseDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@CMI.Utilities.Transkribus.Properties.TranskribusClassifierURL@@")]
        public string TranskribusClassifierURL {
            get {
                return ((string)(this["TranskribusClassifierURL"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@CMI.Utilities.Transkribus.Properties.TranskribusDecodeURL@@")]
        public string TranskribusDecodeURL {
            get {
                return ((string)(this["TranskribusDecodeURL"]));
            }
            set {
                this["TranskribusDecodeURL"] = value;
            }
        }
    }
}
