//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMI.Manager.Onboarding.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class OnboardingPostbackSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static OnboardingPostbackSetting defaultInstance = ((OnboardingPostbackSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OnboardingPostbackSetting())));
        
        public static OnboardingPostbackSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:12972")]
        public string PostbackBaseUrl {
            get {
                return ((string)(this["PostbackBaseUrl"]));
            }
        }
    }
}
