//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMI.Manager.Onboarding.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class OnboardingSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static OnboardingSetting defaultInstance = ((OnboardingSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OnboardingSetting())));
        
        public static OnboardingSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:12972")]
        public string PostbackBaseUrl {
            get {
                return ((string)(this["PostbackBaseUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@ConnectorClientId@@")]
        public string ConnectorClientId {
            get {
                return ((string)(this["ConnectorClientId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@ConnectorClientSecret@@")]
        public string ConnectorClientSecret {
            get {
                return ((string)(this["ConnectorClientSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string ConnectorTokenExpiration {
            get {
                return ((string)(this["ConnectorTokenExpiration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@ConnectorBaseUrl@@")]
        public string ConnectorBaseUrl {
            get {
                return ((string)(this["ConnectorBaseUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1800000")]
        public int TimerProcessDueTime {
            get {
                return ((int)(this["TimerProcessDueTime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@OnboardingCallbackSuccess@@")]
        public string OnboardingCallbackSuccessUrl {
            get {
                return ((string)(this["OnboardingCallbackSuccessUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@OnboardingCallbackWarn@@")]
        public string OnboardingCallbackWarnUrl {
            get {
                return ((string)(this["OnboardingCallbackWarnUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@OnboardingCallbackError@@")]
        public string OnboardingCallbackErrorUrl {
            get {
                return ((string)(this["OnboardingCallbackErrorUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@OnboardingCallbackReview@@")]
        public string OnboardingCallbackReviewUrl {
            get {
                return ((string)(this["OnboardingCallbackReviewUrl"]));
            }
        }
    }
}
