//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMI.Contract.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMI.Contract.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akzession.
        /// </summary>
        internal static string Akzession {
            get {
                return ResourceManager.GetString("Akzession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiv.
        /// </summary>
        internal static string Archiv {
            get {
                return ResourceManager.GetString("Archiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestand.
        /// </summary>
        internal static string Bestand {
            get {
                return ResourceManager.GetString("Bestand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beständeserie.
        /// </summary>
        internal static string Beständeserie {
            get {
                return ResourceManager.GetString("Beständeserie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument.
        /// </summary>
        internal static string Dokument {
            get {
                return ResourceManager.GetString("Dokument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier.
        /// </summary>
        internal static string Dossier {
            get {
                return ResourceManager.GetString("Dossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frei zugänglich.
        /// </summary>
        internal static string Frei_zugänglich {
            get {
                return ResourceManager.GetString("Frei zugänglich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptabteilung.
        /// </summary>
        internal static string Hauptabteilung {
            get {
                return ResourceManager.GetString("Hauptabteilung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Schutzfrist.
        /// </summary>
        internal static string In_Schutzfrist {
            get {
                return ResourceManager.GetString("In Schutzfrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfung nötig.
        /// </summary>
        internal static string Prüfung_nötig {
            get {
                return ResourceManager.GetString("Prüfung nötig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        internal static string Serie {
            get {
                return ResourceManager.GetString("Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subdossier.
        /// </summary>
        internal static string Subdossier {
            get {
                return ResourceManager.GetString("Subdossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilbestand.
        /// </summary>
        internal static string Teilbestand {
            get {
                return ResourceManager.GetString("Teilbestand", resourceCulture);
            }
        }
    }
}
