//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMI.Manager.Index.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bestand")]
        public string LevelAggregationIdentifier {
            get {
                return ((string)(this["LevelAggregationIdentifier"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"metadata=res://*/CMI.Access.Sql.Viaduc.EF.Viaduc.csdl|res://*/CMI.Access.Sql.Viaduc.EF.Viaduc.ssdl|res://*/CMI.Access.Sql.Viaduc.EF.Viaduc.msl;provider=System.Data.SqlClient;provider connection string='Data Source=localhost;initial catalog=Viaduc;Trusted_Connection=True;MultipleActiveResultSets=True;App=EntityFramework'")]
        public string ConnectionStringEF {
            get {
                return ((string)(this["ConnectionStringEF"]));
            }
        }
    }
}
