//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMI.Utilities.DigitalRepository.CreateTestDataHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@CMI.Utilities.DigitalRepository.CreateTestDataHelper.Properties.OraclePort@@")]
        public string OraclePort {
            get {
                return ((string)(this["OraclePort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OracleSID {
            get {
                return ((string)(this["OracleSID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@CMI.Utilities.DigitalRepository.CreateTestDataHelper.Properties.OracleSchemaNam" +
            "e@@")]
        public string OracleSchemaName {
            get {
                return ((string)(this["OracleSchemaName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@CMI.Utilities.DigitalRepository.CreateTestDataHelper.Properties.OracleHost@@")]
        public string OracleHost {
            get {
                return ((string)(this["OracleHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@CMI.Utilities.DigitalRepository.CreateTestDataHelper.Properties.OracleServiceNa" +
            "me@@")]
        public string OracleServiceName {
            get {
                return ((string)(this["OracleServiceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@CMI.Utilities.DigitalRepository.CreateTestDataHelper.Properties.AlfrescoService" +
            "Url@@")]
        public string AlfrescoServiceUrl {
            get {
                return ((string)(this["AlfrescoServiceUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@CMI.Utilities.DigitalRepository.CreateTestDataHelper.Properties.Settings.Oracle" +
            "User@@")]
        public string OracleUser {
            get {
                return ((string)(this["OracleUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@CMI.Utilities.DigitalRepository.CreateTestDataHelper.Properties.Settings.Oracle" +
            "Password@@")]
        public string OraclePassword {
            get {
                return ((string)(this["OraclePassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@CMI.Utilities.DigitalRepository.CreateTestDataHelper.Properties.Settings.Alfres" +
            "coUser@@")]
        public string AlfrescoUser {
            get {
                return ((string)(this["AlfrescoUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@CMI.Utilities.DigitalRepository.CreateTestDataHelper.Properties.Settings.Alfres" +
            "coPassword@@")]
        public string AlfrescoPassword {
            get {
                return ((string)(this["AlfrescoPassword"]));
            }
        }
    }
}
