update ApplicationRoleFeature
	set FeatureId = 'AuftragsuebersichtEinsichtsgesucheDigitalisierungAusloesenAusfuehren'
	where FeatureId = 'AuftragsuebersichtEinsichtsgesucheDigitalisierungsauftragAusfuehren';