//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMI.Manager.Asset.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class IiifManifest : global::System.Configuration.ApplicationSettingsBase {
        
        private static IiifManifest defaultInstance = ((IiifManifest)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IiifManifest())));
        
        public static IiifManifest Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://viaducdev.cmiag.ch/clientdev/iiif/")]
        public string ApiServerUri {
            get {
                return ((string)(this["ApiServerUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://viaducdev.cmiag.ch/image/")]
        public string ImageServerUri {
            get {
                return ((string)(this["ImageServerUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://viaducdev.cmiag.ch/clientdev/files/manifests/")]
        public string PublicManifestWebUri {
            get {
                return ((string)(this["PublicManifestWebUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://viaducdev.cmiag.ch/clientdev/")]
        public string PublicDetailRecordUri {
            get {
                return ((string)(this["PublicDetailRecordUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://viaducdev.cmiag.ch/clientdev/files/ocr/")]
        public string PublicOcrWebUri {
            get {
                return ((string)(this["PublicOcrWebUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://viaducdev.cmiag.ch/clientdev/files/content/")]
        public string PublicContentWebUri {
            get {
                return ((string)(this["PublicContentWebUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S3")]
        public string DataStorageProvider {
            get {
                return ((string)(this["DataStorageProvider"]));
            }
        }
    }
}
